#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
export PYTHONPATH="$HERE/usr/lib/python3.10:$HERE/usr/lib/python3.10/lib-dynload:$HERE/usr/lib/python3.10/site-packages"
export LD_LIBRARY_PATH="$HERE/usr/lib"
export TCL_LIBRARY="$HERE/usr/share/tcltk/tcl8.6"
export TK_LIBRARY="$HERE/usr/share/tcltk/tk8.6"
exec "$HERE/usr/bin/python3" "$HERE/usr/bin/painel.py" "$@"
